export const categories = []
export const products =  [
  {
    catalog: ["Аxуйн хэрэглээ"],
    updatedAt: { _seconds: 1638261568, _nanoseconds: 723000000 },
    size: "2л",
    price: "3480",
    name: "mountain dev том",
    images: ["https://cdn.geresee.tk/us_undaa/laimon_orange.jpg"],
    id: "00lASlmTHwulN8BXVEQn",
    available: "Байхгүй",
  },
  {
    id: "063cKtRf3XA9hKv9dVVy",
    available: true,
    name: "laimon оранж",
    updatedAt: { _nanoseconds: 432000000, _seconds: 1634481333 },
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/laimon_orange.jpg"],
    size: "0.5л",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2060",
  },
  {
    size: "1ш",
    name: "Раффаэлло1",
    available: true,
    images: ["https://cdn.geresee.tk/Амттан/Раффаэлло1.jpg"],
    price: "10000",
    catalog: ["Амттан"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    updatedAt: { _seconds: 1627213941, _nanoseconds: 563000000 },
    id: "08xb68YCETqTlof6SXg8",
  },
  {
    size: "1кг",
    price: "4260",
    id: "0NoxNFqKWGxkbLn8ABIN",
    name: "слава гурвалжин будаа",
    available: true,
    catalog: ["Үр тариа"],
    images: ["https://cdn.geresee.tk/ur_taria/slava_gurvaljin_budaa.jpg"],
    updatedAt: { _seconds: 1627213911, _nanoseconds: 19000000 },
    keyWords: ["будаа"],  
  },
  {
    id: "0OyFcNof4VHPy4jhDBGK",
    available: true,
    updatedAt: { _seconds: 1627213850, _nanoseconds: 889000000 },
    catalog: ["Мах махан бүтээгдэхүүн"],
    keyWords: [],
    size: "500г",
    name: "Алтан салями бүтэн утлагат хиам",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /altan-saliam-buten-utalgat-hiam.jpg",
    ],
    price: "7000",
  },
  {
    id: "0mshOW1zzayjvKMjqpHb",
    size: "0.5л",
    price: "1022",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images:
      "https://firebasestorage.googleapis.com/v0/b/crawler-ef1f1.appspot.com/o/products%2FupdatedImages%2Fcoca-cola_original_taste_1l_72842_T1.jpeg?alt=media&token=58bfbfcc-bde3-4610-873f-e9f3af4f15fe",
    catalog: ["Шингэн хүнс"],
    updatedAt: { _seconds: 1638167377, _nanoseconds: 810000000 },
    name: "punch",
    available: "Байхгүй",
  },
  {
    updatedAt: { _seconds: 1627213870, _nanoseconds: 933000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "1810",
    name: "талх онцгой хар",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    size: "1",
    available: true,
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/talh_ontsgoi_har.jpg",
    ],
    id: "0s0a2fTQ3eXfl6gZ8fcm",
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/lavsha_tuuzan_goimon.jpg",
    ],
    updatedAt: { _nanoseconds: 833000000, _seconds: 1627214018 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    available: true,
    name: "лавша туузан гоймон",
    price: "1280",
    id: "16YBtA2pXXrwOylucZxi",
    size: "300гр",
  },
  {
    size: "500гр",
    id: "17XF5ypxWqfJ8DYrnqok",
    available: true,
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    price: "4000",
    updatedAt: { _seconds: 1627214031, _nanoseconds: 868000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ur_taria_guril.jpg",
    ],
    name: "Үр тариа гурил",
  },
  {
    size: "1ш",
    name: "ариун цаасан алчуур",
    available: true,
    price: "1320",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/aruin_tsaasan_alchuur.jpg"],
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    id: "1UzYWHajCMymoKQ4PXlZ",
    updatedAt: { _seconds: 1627214013, _nanoseconds: 938000000 },
    catalog: ["Аxуйн хэрэглээ"],
  },
  {
    size: "900г",
    id: "1ZyOmxWS17yt3EFjmpNg",
    name: "Талын монгол кальцтай бууз",
    updatedAt: { _seconds: 1627213857, _nanoseconds: 836000000 },
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /taliin-mongol-honi-kaltstai-buuz.jpg",
    ],
    keyWords: [],
    available: true,
    catalog: ["Мах махан бүтээгдэхүүн"],
    price: "9000",
  },
  {
    catalog: ["Нөөшилсөн хүнс"],
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Лайс-Шашлык.jpg"],
    id: "1fcZhJjvDmsYCUcmaNYU",
    size: "1ш",
    updatedAt: { _nanoseconds: 517000000, _seconds: 1627213994 },
    name: "Лайс-Шашлык",
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "3800",
    available: true,
  },
  {
    updatedAt: { _seconds: 1638167438, _nanoseconds: 910000000 },
    id: "1uziwkwwGbAJokqJOk49",
    available: "Байхгүй",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/apple_kagome.jpg"],
    name: "punch",
    size: "0.5л",
    catalog: ["Шингэн хүнс"],
    price: "1022",
  },
  {
    catalog: ["Нөөшилсөн хүнс"],
    price: "2500",
    id: "204wey2nf59NfkkOhGtU",
    available: true,
    name: "Бэлэн гоймон(Jin Ramen)",
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон(Jin Ramen).jpg",
    ],
    updatedAt: { _nanoseconds: 101000000, _seconds: 1627213955 },
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    size: "1ш",
  },
  {
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/авакода тос.jpg"],
    updatedAt: { _nanoseconds: 759000000, _seconds: 1627213861 },
    price: "30000",
    size: "1ш",
    available: true,
    name: "Авакода тос",
    id: "2A5Xvfw9TmMLNRAFx0X6",
  },
  {
    images: ["https://cdn.geresee.tk/us_undaa/hujirt_tom.jpg"],
    updatedAt: { _seconds: 1627214017, _nanoseconds: 856000000 },
    name: "Хужирт цэвэр ус том",
    keyWords: ["кола", "жүүс", "шүүс", "уух"],
    size: "1.5л",
    catalog: ["Шингэн хүнс"],
    id: "2VDVNsiHcbOLAdiLH3y5",
    available: true,
    price: "2130",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Боловсруулсан хүнс"],
    id: "2k3sbvqY9nQLrgyrpE11",
    price: "3000",
    name: "Цөцгийн тос Симпли",
    size: "1ш",
    available: true,
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/simply.jpg"],
    updatedAt: { _seconds: 1627213898, _nanoseconds: 531000000 },
  },
  {
    price: "6000",
    size: "500г",
    catalog: ["Мах махан бүтээгдэхүүн"],
    available: true,
    name: "Аянчин хагас утлагат хиам",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /ayanchin-hagas-utalgat-hiam-front.jpg",
    ],
    keyWords: [],
    updatedAt: { _seconds: 1627213851, _nanoseconds: 181000000 },
    id: "3ESGCcq8A702MrBAimxY",
  },
  {
    size: "850г",
    price: "7000",
    available: true,
    catalog: ["Мах махан бүтээгдэхүүн"],
    updatedAt: { _nanoseconds: 208000000, _seconds: 1627213854 },
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /orgio-tahian-mah-front.jpg",
    ],
    id: "3VgH8GhEwMFjBY5TFTCe",
    keyWords: [],
    name: "Оргио тахианий гуя",
  },
  {
    updatedAt: { _nanoseconds: 650000000, _seconds: 1627213933 },
    name: "Варейн-гүзээлзгэнэ",
    available: true,
    size: "1ш",
    id: "3VtFzU7iFO9PAIFoSNvv",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/Варейн-гүзээлзгэнэ.jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
    price: "7000",
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/lavsha_tuuzan_goimon_songinotoi.jpg",
    ],
    updatedAt: { _nanoseconds: 780000000, _seconds: 1627213859 },
    id: "3ZnbVmKPe4J1ZA13zSYn",
    available: true,
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "300гр",
    price: "1280",
    name: "лавша туузан гоймон сонгинотой",
  },
  {
    updatedAt: { _seconds: 1627213925, _nanoseconds: 57000000 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    catalog: ["Шингэн хүнс"],
    id: "3cW4U1t9zVDiOIH6IRwv",
    name: "жижиг cola",
    price: "1500",
    size: "0.5л",
    available: true,
    images: ["https://cdn.geresee.tk/us_undaa/coca_cola_husliin.png"],
  },
  {
    updatedAt: { _nanoseconds: 858000000, _seconds: 1627214016 },
    images: ["https://cdn.geresee.tk/tea_coffee/jacobs_coffee.jpg"],
    name: "Jacobs кофе",
    keyWords: [],
    catalog: ["Цай, кофе"],
    price: "15000",
    id: "3eDCkYDJJFHjfAEsfwfv",
    size: "50г",
    available: true,
  },
  {
    catalog: ["Шингэн хүнс"],
    updatedAt: { _seconds: 1627213877, _nanoseconds: 1000000 },
    images: ["https://cdn.geresee.tk/us_undaa/mountain_dev_big.jpg"],
    available: true,
    name: "mountain dev том",
    size: "2л",
    id: "4EAMDogVUA823M7GmHL9",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "3480",
  },
  {
    catalog: ["Архи, Пиво"],
    updatedAt: { _seconds: 1627214020, _nanoseconds: 826000000 },
    available: true,
    keyWords: ["шар айраг", "дарс", "вино", "согтууруулах ундаа"],
    size: "750мл",
    images: [
      "https://cdn.geresee.tk/vine%26beer/yellow_tail_jammy_red_roo.jpg",
    ],
    id: "57q9aCJ7APsukenNZODB",
    price: "28130",
    name: "yellow tail jammy red roo",
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/farfalle_goimon.jpg",
    ],
    updatedAt: { _seconds: 1627213862, _nanoseconds: 838000000 },
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    available: true,
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "3750",
    name: "farfalle гоймон",
    id: "5iDW3HMZxO1vZH6RnMOB",
    size: "500гр",
  },
  {
    updatedAt: { _seconds: 1627213871, _nanoseconds: 448000000 },
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/minii_mongoliin_suu.jpg",
    ],
    size: "2л",
    available: true,
    price: "2300",
    name: "миний монголын сүү",
    keyWords: ["сүү", "тараг", "аарц"],
    id: "5t53McgKumRDLq5j1ga1",
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
  },
  {
    keyWords: [],
    price: "30000",
    images: [
      "https://cdn.geresee.tk/tea_coffee/Жүжүбэ зөгийн балны уусмал.jpg",
    ],
    catalog: ["Цай, кофе"],
    size: "1ш",
    name: "Жүжүбэ зөгийн балны уусмал",
    updatedAt: { _seconds: 1627213938, _nanoseconds: 935000000 },
    id: "5w1D8sCh9pVpCtUG6eYH",
    available: true,
  },
  {
    catalog: ["Нөөшилсөн хүнс"],
    id: "62r4mRXYLabHVqsZiJ3g",
    updatedAt: { _nanoseconds: 453000000, _seconds: 1627213951 },
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    available: true,
    price: "5000",
    name: "Хот дог3",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Хот дог3.jpg"],
    size: "1ш",
  },
  {
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _nanoseconds: 870000000, _seconds: 1627213986 },
    size: "1ш",
    available: true,
    id: "72MlfbxXDShP5BaoFGow",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/бүлгүги соус (үхрийн) 1.jpg",
    ],
    price: "8000",
    name: "Бүлгүги соус (үхрийн) 1",
  },
  {
    size: "1ш",
    name: "Принглэс-Sour Cream & Onion",
    catalog: ["Нөөшилсөн хүнс"],
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Принглэс-Sour Cream %26 Onion.jpg",
    ],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "3800",
    updatedAt: { _seconds: 1627213900, _nanoseconds: 80000000 },
    id: "75yTWi8UrSTGPIgP6u49",
    available: true,
  },
  {
    name: "жүрж фанта том",
    size: "2л",
    catalog: ["Шингэн хүнс"],
    price: "2840",
    available: true,
    id: "7PaPZAihv1W2fiZG0YNf",
    updatedAt: { _nanoseconds: 576000000, _seconds: 1627213877 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/orange_fanta.jpg"],
  },
  {
    available: true,
    size: "2л",
    price: "2840",
    id: "7RSrH4hrIcr1LpRD8pvK",
    images: ["https://cdn.geresee.tk/us_undaa/apple_fanta_big.jpg"],
    updatedAt: { _seconds: 1627213888, _nanoseconds: 262000000 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "алим фанта том",
    catalog: ["Шингэн хүнс"],
  },
  {
    available: true,
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Хот дог.jpg"],
    catalog: ["Нөөшилсөн хүнс"],
    size: "1ш",
    name: "Хот дог",
    updatedAt: { _nanoseconds: 455000000, _seconds: 1627213995 },
    id: "7jeQSusKZMryDh3WE78Q",
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "5000",
  },
  {
    available: true,
    size: "6",
    price: "2600",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _seconds: 1627213989, _nanoseconds: 728000000 },
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/eldevtei_guril.jpg",
    ],
    id: "7tJF8JbAhhEYeoRR7cVk",
    name: "элдэвтэй гурил",
  },
  {
    id: "8CevteVzPz9wpCfOTIn0",
    updatedAt: { _nanoseconds: 728000000, _seconds: 1627213894 },
    price: "5500",
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "1ш",
    available: true,
    name: "Шар буурцгийн зуурмаг 2",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/шар буурцгийн зуурмаг 2.jpg",
    ],
  },
  {
    keyWords: ["будаа"],
    size: "2кг",
    price: "12110",
    id: "8RvOpQdCJbK7vCeytOGY",
    catalog: ["Үр тариа"],
    name: "сакура будаа том",
    images: ["https://cdn.geresee.tk/ur_taria/sakura_budaa_tom.jpg"],
    updatedAt: { _seconds: 1627213953, _nanoseconds: 296000000 },
    available: true,
  },
  {
    keyWords: ["tobacco"],
    size: "1ш",
    price: "3960",
    name: "Парламент night blue",
    images: ["https://cdn.geresee.tk/cigarettes/Парламент night blue.jpg"],
    id: "8SYb9kxSLzEcbiaS49o5",
    catalog: ["Тамхи"],
    available: true,
    updatedAt: { _seconds: 1627214002, _nanoseconds: 248000000 },
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/altan_taria_guril_deed.jpg",
    ],
    available: true,
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    size: "1kg",
    price: "1620",
    updatedAt: { _seconds: 1627213860, _nanoseconds: 825000000 },
    id: "8fV7c4nVG3kUT7eiUB7S",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "алтан тариа дээд гурил",
  },
  {
    images: ["https://cdn.geresee.tk/vine%26beer/JP_Chenet_Pinot_Noir.jpg"],
    id: "8forNMBdjGu6GpTxCsTM",
    available: true,
    price: "26000",
    updatedAt: { _seconds: 1627213863, _nanoseconds: 979000000 },
    size: "750мл",
    name: "JP Chenet Pinot Noi",
    catalog: ["Архи, Пиво"],
    keyWords: ["шар айраг", "дарс", "вино", "согтууруулах ундаа"],
  },
  {
    id: "8iw4UtERF3aqFzR5UnXL",
    keyWords: [],
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/sarmis.jpg"],
    name: "сармис",
    updatedAt: { _seconds: 1627213909, _nanoseconds: 374000000 },
    price: "1300",
    catalog: ["Хүнсний ногоо"],
    available: true,
    size: "1кг",
  },
  {
    images: ["https://cdn.geresee.tk/Амттан/М%26М.jpg"],
    updatedAt: { _nanoseconds: 51000000, _seconds: 1627213903 },
    name: "М&М",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    catalog: ["Амттан"],
    id: "8r0z8d5UR1oEk3CJSLTN",
    available: true,
    size: "1ш",
    price: "12800",
  },
  {
    images: ["https://cdn.geresee.tk/ahuin_hereglee/sofy_odriin.jpg"],
    price: "3350",
    id: "8zsgsbceD8BKPPbIDA6c",
    size: "10ш",
    available: true,
    updatedAt: { _seconds: 1627214010, _nanoseconds: 23000000 },
    catalog: ["Аxуйн хэрэглээ"],
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    name: "sofy odriin",
  },
  {
    catalog: ["Боловсруулсан хүнс"],
    name: "Карри (халун ногоо их)",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _seconds: 1627213890, _nanoseconds: 996000000 },
    price: "5000",
    available: true,
    id: "94twAAPytmUw4jiAXK4f",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/карри (халун ногоо их).jpg",
    ],
    size: "1ш",
  },
  {
    available: true,
    updatedAt: { _nanoseconds: 569000000, _seconds: 1627213992 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "Шар буурцгийн зуурмаг 1",
    id: "9AsSrp49HEoDKJYgYYHr",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/шар буурцгийн зуурмаг 1.jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
    size: "1ш",
    price: "5500",
  },
  {
    name: "Улаанбаатар бүхэл үрийн гурил",
    id: "9nssqyylSvVntMG8PV7x",
    size: "1kg",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ulaanbaatar_guril_buhel_uriin.jpg",
    ],
    price: "2200",
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213967, _nanoseconds: 117000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
  },
  {
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    updatedAt: { _seconds: 1627214015, _nanoseconds: 880000000 },
    price: "2300",
    available: true,
    size: "2л",
    keyWords: ["сүү", "тараг", "аарц"],
    id: "AL9pwyE52wdXFMv1DHYA",
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/amtlag_tarag_chavga.jpg",
    ],
    name: "амтлаг тараг чавга жимстэй",
  },
  {
    id: "AbGDB4FPPrDErPfJQrbF",
    size: "20ш",
    updatedAt: { _seconds: 1627213923, _nanoseconds: 321000000 },
    name: "бөөр хамгаалах цай",
    price: "7440",
    keyWords: [],
    images: ["https://cdn.geresee.tk/tea_coffee/boor_hamgaalah_tsai.jpg"],
    catalog: ["Цай, кофе"],
    available: true,
  },
  {
    available: true,
    name: "лавша туузан гоймон  луувантай",
    updatedAt: { _seconds: 1627214034, _nanoseconds: 875000000 },
    id: "Bh37lfWNAUaYJIyQLpxB",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "1280",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/lavsha_tuuzan_goimon_luuvantai.jpg",
    ],
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    size: "300гр",
  },
  {
    catalog: ["Шингэн хүнс"],
    id: "BnHP0QbjLAVrBEqSv9O0",
    size: "2л",
    price: "2840",
    name: "тоор жимс фанта том",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    updatedAt: { _seconds: 1627214044, _nanoseconds: 44000000 },
    images: ["https://cdn.geresee.tk/us_undaa/peach_fanta_big.jpg"],
    available: true,
  },
  {
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /slava-tahia-guy-front.jpg",
    ],
    available: true,
    id: "BqktZOavte3T7EmOVAA0",
    catalog: ["Мах махан бүтээгдэхүүн"],
    updatedAt: { _nanoseconds: 213000000, _seconds: 1627213856 },
    keyWords: [],
    size: "1кг",
    name: "Слава тахианий гуя",
    price: "6160",
  },
  {
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/sprite_light.jpg"],
    price: "0.5л",
    available: true,
    size: "1500",
    name: "жижиг спрайт",
    updatedAt: { _seconds: 1627213993, _nanoseconds: 525000000 },
    id: "Bqp2xWQrvdZE6ZtxdEu6",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
  },
  {
    updatedAt: { _nanoseconds: 769000000, _seconds: 1627213930 },
    available: true,
    price: "1700",
    images: ["https://cdn.geresee.tk/us_undaa/tomate_kagome.jpg"],
    id: "CKnpEB0BW1UOaszBdK6S",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    catalog: ["Шингэн хүнс"],
    size: "0.5л",
    name: "томатэ кагомэ",
  },
  {
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /nomad-buurunhii-mah.jpg",
    ],
    updatedAt: { _seconds: 1627213853, _nanoseconds: 298000000 },
    catalog: ["Шингэн"],
    id: "CQ2GweptsuqXYKY4jL9I",
    available: true,
    size: "900г",
    price: "11000",
    keyWords: [],
    name: "Номад бөөрөнхий мах",
  },
  {
    catalog: ["Шингэн хүнс"],
    keyWords: ["жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/hujirt.jpg"],
    id: "CbyUsqAQsDGm3QKCfft5",
    available: true,
    name: "Хужирт цэвэр ус",
    size: "330мл",
    price: "1110",
    updatedAt: { _nanoseconds: 539000000, _seconds: 1627213917 },
  },
  {
    price: "4500",
    catalog: ["Боловсруулсан хүнс"],
    id: "CzA5c9715B4Uk5oRiXtC",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    size: "1ш",
    name: "Халуун ногоотой чихэрлэг чили соус жижиг",
    updatedAt: { _seconds: 1627213969, _nanoseconds: 942000000 },
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/халуун ногоотой чихэрлэг чили соус жижиг.jpg",
    ],
  },
  {
    size: "500гр",
    id: "E0bcDVgMXWpIylaHkI30",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    updatedAt: { _seconds: 1627213975, _nanoseconds: 584000000 },
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ur_taria_buhel_uriin_guril.jpg",
    ],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    name: "үр тариа бүхэл үрийн гурил",
    price: "3400",
  },
  {
    images: ["https://cdn.geresee.tk/Амттан/мэрси 2.jpg"],
    updatedAt: { _nanoseconds: 831000000, _seconds: 1627214027 },
    catalog: ["Амттан"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    name: "мэрси 2",
    size: "1ш",
    price: "30000",
    id: "EJmyjGvbeF88aOEm23we",
    available: true,
  },
  {
    price: "4000",
    size: "500г",
    name: "Frankfurter чанамал утлагат зайдас",
    available: true,
    id: "EQhqsELo30PtHtbCtyrZ",
    updatedAt: { _seconds: 1627213851, _nanoseconds: 755000000 },
    keyWords: [],
    catalog: ["Мах махан бүтээгдэхүүн"],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /frankfuter-chanamal-utalgat-zaidas.jpg",
    ],
  },
  {
    updatedAt: { _seconds: 1627213865, _nanoseconds: 591000000 },
    id: "Eday8oD5EOdpRxxzBY92",
    catalog: ["Тамхи"],
    name: "Састер",
    keyWords: ["tobacco"],
    available: true,
    size: "1ш",
    images: ["https://cdn.geresee.tk/cigarettes/Кастер.jpg"],
    price: "3960",
  },
  {
    available: true,
    price: "1700",
    updatedAt: { _seconds: 1627213878, _nanoseconds: 924000000 },
    name: "липтон Ногоон цай ",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    catalog: ["Шингэн хүнс"],
    size: "0.5л",
    id: "EdsqfzNS8Bb7RAK89m2F",
    images: ["https://cdn.geresee.tk/us_undaa/green_tea_lipton.jpg"],
  },
  {
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Хот дог1.jpg"],
    catalog: ["Нөөшилсөн хүнс"],
    size: "1ш",
    available: true,
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    name: "Хот дог1",
    updatedAt: { _seconds: 1627214032, _nanoseconds: 866000000 },
    id: "EtUukgAlyU00x06aoaLY",
    price: "5000",
  },
  {
    id: "FDu56CnZHWQAm0HMIOcU",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Чинжүүний салад.jpg"],
    available: true,
    price: "3500",
    size: "1ш",
    name: "Чинжүүний салад",
    updatedAt: { _seconds: 1627213875, _nanoseconds: 260000000 },
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    available: true,
    updatedAt: { _nanoseconds: 565000000, _seconds: 1627213873 },
    price: "2800",
    name: "Доритос-жижиг(cheese)",
    catalog: ["Нөөшилсөн хүнс"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    id: "GTssctnDUGqbEeFgrlUp",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Доритос-жижиг(cheese).jpg"],
    size: "1ш",
  },
  {
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    name: "Улаанбаатар дээд 1 дүгээр гурил",
    updatedAt: { _seconds: 1627213948, _nanoseconds: 750000000 },
    price: "1750",
    id: "GnFMhz0GorA11aUj6P9j",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ulaan_baatar_guril_1.jpg",
    ],
    available: true,
    size: "1kg",
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    keyWords: [],
    catalog: ["Мах махан бүтээгдэхүүн"],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /byslagt-davhar-utalgat-hiam.jpg",
    ],
    name: "Бяслагт давхар утлагат хиам",
    updatedAt: { _nanoseconds: 467000000, _seconds: 1627213851 },
    price: "7700",
    id: "HdFReDaf1nih9bADGT73",
    size: "500г",
    available: true,
  },
  {
    name: "tide угаалгын нунтаг",
    catalog: ["Аxуйн хэрэглээ"],
    size: "3кг",
    price: "18700",
    updatedAt: { _nanoseconds: 519000000, _seconds: 1627213895 },
    id: "HuoTpRSCUfqQf97cKfMI",
    available: true,
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    images: ["https://cdn.geresee.tk/ahuin_hereglee/tide_tom.jpg"],
  },
  {
    images: ["https://cdn.geresee.tk/Амттан/мэрси том 1.jpg"],
    price: "50000",
    id: "IlxAsKTMn4nNqggBmbPC",
    updatedAt: { _nanoseconds: 908000000, _seconds: 1627213970 },
    catalog: ["Амттан"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    size: "1ш",
    name: "мэрси том 1",
    available: true,
  },
  {
    catalog: ["Жимс жимсгэнэ"],
    updatedAt: { _nanoseconds: 780000000, _seconds: 1627214023 },
    id: "IzrT2ZmPkbP0MIipKpK5",
    price: "11900",
    keyWords: ["fruit"],
    size: "1kg",
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/mandarin.jpg"],
    name: "мандарин",
    available: true,
  },
  {
    images: ["https://cdn.geresee.tk/tea_coffee/nescafe_coffee_gold.jpg"],
    keyWords: [],
    size: "20ш",
    price: "7800",
    name: "тайвшруулах цай",
    catalog: ["Цай, кофе"],
    available: true,
    updatedAt: { _seconds: 1627213929, _nanoseconds: 769000000 },
    id: "JK3rda1rseeBqQua3MPc",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _seconds: 1627213912, _nanoseconds: 701000000 },
    available: true,
    id: "JPzqrveESl33YebVwxBB",
    size: "1ш",
    price: "10000",
    name: "Сыр1-Hochland",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Сыр1-Hochland.jpg"],
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    name: "Талын монгол хунчиртай банш",
    updatedAt: { _seconds: 1627213857, _nanoseconds: 238000000 },
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /taliin-mongol-honi-hunchirtai-bansh.jpg",
    ],
    keyWords: [],
    price: "6000",
    available: true,
    catalog: ["Мах махан бүтээгдэхүүн"],
    id: "JbGPiQumTb52UtrJxZw2",
    size: "800г",
  },
  {
    available: true,
    price: "3960",
    name: "Попкорн",
    id: "JgLXmvBy11ixNGZDWeEJ",
    images: ["https://cdn.geresee.tk/Амттан/поп корн.jpg"],
    catalog: ["Амттан"],
    updatedAt: { _seconds: 1627213981, _nanoseconds: 211000000 },
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    size: "1ш",
  },
  {
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Цөцгийн тос.jpg"],
    available: true,
    price: "8000",
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627214047, _nanoseconds: 122000000 },
    id: "JlCV1gVhXSHOoKetM5Yz",
    name: "Цөцгийн тос",
    size: "1ш",
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    price: "10000",
    size: "1ш",
    id: "JosPzl5kD0Z05lqvgSxn",
    available: true,
    catalog: ["Амттан"],
    name: "Раффаэлло",
    images: ["https://cdn.geresee.tk/Амттан/Раффаэлло.jpg"],
    updatedAt: { _seconds: 1627213961, _nanoseconds: 549000000 },
  },
  {
    updatedAt: { _seconds: 1627213911, _nanoseconds: 863000000 },
    keyWords: [],
    available: true,
    name: "Yellow label цай ",
    price: "3240",
    id: "Jp0kctQrXBJ6NXojWX9w",
    size: "25ш",
    images: ["https://cdn.geresee.tk/tea_coffee/yellow_label.jpg"],
    catalog: ["Цай, кофе"],
  },
  {
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "Хан боргоцой фанта том",
    id: "JuoJKRctLFjS2AwAePd3",
    images: ["https://cdn.geresee.tk/us_undaa/pineapple_fanta.jpg"],
    catalog: ["Шингэн хүнс"],
    price: "2840",
    available: true,
    updatedAt: { _seconds: 1627213865, _nanoseconds: 187000000 },
    size: "2л",
  },
  {
    id: "Jwiu9rUhQCGLcB3dg4Es",
    size: "2л",
    keyWords: ["сүү", "тараг", "аарц"],
    name: "дээж тараг",
    price: "2300",
    images: ["https://cdn.geresee.tk/Milk_and_milk_products/deej_tarag.jpg"],
    updatedAt: { _nanoseconds: 13000000, _seconds: 1627214011 },
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    available: true,
  },
  {
    catalog: ["Шингэн хүнс"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    id: "KHxJA1k9jo2EM2gnGMvI",
    size: "350мл",
    images: ["https://cdn.geresee.tk/us_undaa/cola_can.jpg"],
    updatedAt: { _seconds: 1627213867, _nanoseconds: 722000000 },
    available: true,
    price: "1900",
    name: "лаазалсан кола",
  },
  {
    size: "1ш",
    name: "Кэтчуп",
    id: "KLRyzYjyjudNNP53ombi",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _nanoseconds: 912000000, _seconds: 1627213915 },
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/кэтчуп.jpg"],
    available: true,
    price: "10000",
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    id: "KOrhimxfGRhJ4MPB7Bio",
    price: "6000",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/сэриал 2.jpg"],
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _nanoseconds: 557000000, _seconds: 1627213883 },
    name: "Сэриал 2",
    available: true,
    size: "1ш",
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    available: true,
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/luuvan.jpg"],
    id: "KSXhS3R5kzJci3OMGXir",
    catalog: ["Хүнсний ногоо"],
    keyWords: [],
    price: "1940",
    name: "лууван",
    size: "0.5кг",
    updatedAt: { _seconds: 1627214011, _nanoseconds: 989000000 },
  },
  {
    images: ["https://cdn.geresee.tk/Milk_and_milk_products/bio_fit_tarag.jpg"],
    updatedAt: { _seconds: 1627213865, _nanoseconds: 995000000 },
    id: "LfKDqBKfSAmaXXC2qQWi",
    name: "био фит тараг",
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    keyWords: ["сүү", "тараг", "аарц"],
    size: "2л",
    available: true,
    price: "2300",
  },
  {
    catalog: ["Боловсруулсан хүнс"],
    name: "Махеебь майонез",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/махеебь майонез.jpg"],
    updatedAt: { _seconds: 1627213863, _nanoseconds: 212000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    price: "4400",
    id: "Ljy0l9dmGe6ypOnW2gjx",
    size: "1ш",
  },
  {
    price: "4620",
    updatedAt: { _seconds: 1627213858, _nanoseconds: 395000000 },
    size: "300г",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /taliin-mongol-uher-zorson-mah-front.jpg",
    ],
    keyWords: [],
    name: "Талын монгол үхрийн зорсон мах",
    catalog: ["Мах махан бүтээгдэхүүн"],
    id: "Ln2jLWa4zDU9FqxdBpOX",
    available: true,
  },
  {
    catalog: ["Аxуйн хэрэглээ"],
    updatedAt: { _nanoseconds: 832000000, _seconds: 1627213928 },
    available: true,
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    size: "1л",
    id: "M064lRtN9nCnoM5WhGL1",
    price: "8120",
    name: "fairy",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/fairy.jpg"],
  },
  {
    price: "6160",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /slava-tahia-much-front.jpg",
    ],
    id: "MMe9HEXMLLbbyDSSkwSE",
    keyWords: [],
    available: true,
    size: "1кг",
    updatedAt: { _seconds: 1627213856, _nanoseconds: 550000000 },
    name: "Слава тахианий мөч",
    catalog: ["Мах махан бүтээгдэхүүн"],
  },
  {
    id: "MbZuOkRvvxkES8xHgRLr",
    size: "2л",
    images: ["https://cdn.geresee.tk/us_undaa/bonaqua_tom.jpg"],
    price: "1500",
    name: "bonqua ус том",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    catalog: ["Шингэн хүнс"],
    available: true,
    updatedAt: { _nanoseconds: 297000000, _seconds: 1627213936 },
  },
  {
    size: "2л",
    keyWords: ["сүү", "тараг", "аарц"],
    price: "2300",
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/activia_ananas.jpg",
    ],
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    id: "MphZesuvNAHDmbxC4e4w",
    available: true,
    updatedAt: { _seconds: 1627214042, _nanoseconds: 12000000 },
    name: "Хан боргоцой активия тараг",
  },
  {
    price: "3800",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Доритос-том(cheese).jpg"],
    id: "MzaIgbUi9VL3eXCR1GmP",
    size: "1ш",
    available: true,
    catalog: ["Нөөшилсөн хүнс"],
    updatedAt: { _seconds: 1627214024, _nanoseconds: 795000000 },
    name: "Доритос-том(cheese)",
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
  },
  {
    updatedAt: { _seconds: 1627213918, _nanoseconds: 351000000 },
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/халуун чинжүүний зуурмаг 1.jpg",
    ],
    name: "Халуун чинжүүний зуурмаг 1",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    price: "5500",
    catalog: ["Боловсруулсан хүнс"],
    size: "1ш",
    id: "N3mLvDgdlZ3IujELZ51A",
  },
  {
    catalog: ["Амттан"],
    id: "NEe0BwDEtAGY994GPkQT",
    available: true,
    updatedAt: { _seconds: 1627213976, _nanoseconds: 524000000 },
    images: ["https://cdn.geresee.tk/Амттан/мэрси 1.jpg"],
    name: "мэрси 1",
    size: "1ш",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    price: "30000",
  },
  {
    price: "2300",
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/actimel_grape_tarag.jpg",
    ],
    updatedAt: { _nanoseconds: 532000000, _seconds: 1627213901 },
    keyWords: ["сүү", "тараг", "аарц"],
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    name: "актимель тараг",
    id: "NcI3TD87zbW35LbyoyUq",
    available: true,
    size: "2л",
  },
  {
    size: "1kg",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/altan_taria_guril_deediin_deed.jpg",
    ],
    name: "алтан тариа дээдийн дээд гурил",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    id: "NfotFkzuU85DjjhRztg8",
    price: "2200",
    updatedAt: { _seconds: 1627213886, _nanoseconds: 974000000 },
  },
  {
    updatedAt: { _seconds: 1627213921, _nanoseconds: 643000000 },
    size: "",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ulaan_baatar_deed_guril.jpg",
    ],
    price: "",
    name: "Улаанбаатар дээд гурил",
    id: "O6HglWBVfPGA6YUkGwXH",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
  },
  {
    updatedAt: { _seconds: 1627213952, _nanoseconds: 394000000 },
    catalog: ["Боловсруулсан хүнс"],
    size: "1ш",
    id: "OKXTa627Pdh5x2R5McPo",
    available: true,
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/Варейн-бөөрөлзгөнө.jpg",
    ],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "7000",
    name: "Варейн-бөөрөлзгөнө",
  },
  {
    price: "2060",
    images: ["https://cdn.geresee.tk/us_undaa/laimon_fresh.jpg"],
    catalog: ["Шингэн хүнс"],
    name: "laimon fresh",
    updatedAt: { _nanoseconds: 5000000, _seconds: 1627213907 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    size: "0.5л",
    id: "OOn1cuHoC20npqREXEc7",
    available: true,
  },
  {
    updatedAt: { _nanoseconds: 756000000, _seconds: 1627213958 },
    price: "1700",
    catalog: ["Шингэн хүнс"],
    available: true,
    id: "OXbjHGibgIxTz8USpgOP",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    size: "0.5л",
    images: ["https://cdn.geresee.tk/us_undaa/ice_tea_lipton.jpg"],
    name: "липтон мөстэй цай",
  },
  {
    images: ["https://cdn.geresee.tk/us_undaa/laimon_orange_tom.jpg"],
    price: "4500",
    available: true,
    catalog: ["Шингэн хүнс"],
    size: "1.5л",
    updatedAt: { _seconds: 1627213896, _nanoseconds: 304000000 },
    id: "OtxcHtot9dsGlqZ3aavq",
    name: "laimon оранж том",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
  },
  {
    size: "190г",
    updatedAt: { _nanoseconds: 853000000, _seconds: 1627213875 },
    price: "18730",
    catalog: ["Цай, кофе"],
    images: ["https://cdn.geresee.tk/tea_coffee/nescafe_coffe_gold_tom.jpg"],
    id: "PLCGNrdHhixiqucJsHqd",
    name: "Nescafe Gold кофе том",
    keyWords: [],
    available: true,
  },
  {
    id: "PRTtaqXJJIiq4xisIsv0",
    updatedAt: { _nanoseconds: 266000000, _seconds: 1627213914 },
    catalog: ["Аxуйн хэрэглээ"],
    price: "3000",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/tide.jpg"],
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    available: true,
    size: "450г",
    name: "tide угаалгын нунтаг",
  },
  {
    available: true,
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "алтан тариа 1 дүгээр гурил",
    id: "PYB0tk6Se6VLtyb8D6RH",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    updatedAt: { _nanoseconds: 955000000, _seconds: 1627214038 },
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/altan_taria_guril_negdugeer_guril.jpg",
    ],
    size: "1kg",
    price: "1620",
  },
  {
    catalog: ["Архи, Пиво"],
    keyWords: ["шар айраг", "дарс", "вино", "согтууруулах ундаа"],
    updatedAt: { _nanoseconds: 471000000, _seconds: 1627213869 },
    id: "PcqgvAtMgEAPB6sobr6q",
    size: "750мл",
    price: "25130",
    images: ["https://cdn.geresee.tk/vine%26beer/jacobs_creek_classic.jpg"],
    available: true,
    name: "jacobs creek classic",
  },
  {
    size: "1ш",
    available: true,
    id: "Q6nYUbYD5fhV7zBDZpnT",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213947, _nanoseconds: 847000000 },
    price: "8500",
    name: "Компод-черри",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Компод-черри.jpg"],
  },
  {
    catalog: ["Нөөшилсөн хүнс"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    name: "Доритос-жижиг(taco)",
    updatedAt: { _seconds: 1627213910, _nanoseconds: 209000000 },
    size: "1ш",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Доритос-жижиг(taco).jpg"],
    id: "QPPMB0orDuVXsw3x9Vum",
    price: "2800",
    available: true,
  },
  {
    size: "1кг",
    price: "1000",
    updatedAt: { _seconds: 1627213867, _nanoseconds: 280000000 },
    available: true,
    catalog: ["Хүнсний ногоо"],
    id: "QPZE0M8ZXSpZQ3vvxEe3",
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/toms.jpg"],
    name: "төмс",
    keyWords: [],
  },
  {
    available: true,
    size: "8ш",
    name: "sofy Goodnight",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/sofy_oroin.jpg"],
    catalog: ["Аxуйн хэрэглээ"],
    price: "5170",
    id: "QZMO36OR9ht3S9cjFDoM",
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    updatedAt: { _seconds: 1627213999, _nanoseconds: 335000000 },
  },
  {
    catalog: ["Тамхи"],
    id: "RaEefuqdHScuXqEm3wT6",
    keyWords: ["tobacco"],
    price: "3960",
    images: ["https://cdn.geresee.tk/cigarettes/Парламент exotic cruise.jpg"],
    updatedAt: { _seconds: 1627214026, _nanoseconds: 794000000 },
    available: true,
    size: "1ш",
    name: "Парламент exotic cruise",
  },
  {
    id: "RvZb3EMMlJHfND0aG8ws",
    name: "баккус хар",
    available: true,
    size: "350л",
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/black_baccus.jpg"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2100",
    updatedAt: { _nanoseconds: 924000000, _seconds: 1627213956 },
  },
  {
    catalog: ["Шингэн хүнс"],
    id: "Rz6jiIIJz22GjFL1Nki0",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    size: "2л",
    images: ["https://cdn.geresee.tk/us_undaa/sprite_zero_big.jpg"],
    price: "2840",
    updatedAt: { _nanoseconds: 675000000, _seconds: 1627213990 },
    available: true,
    name: "zero спрайт том",
  },
  {
    price: "5000",
    available: true,
    id: "SSwMW8dZTuysiEGtBpNz",
    size: "1ш",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Хот дог2.jpg"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    updatedAt: { _nanoseconds: 645000000, _seconds: 1627213887 },
    name: "Хот дог2",
    catalog: ["Нөөшилсөн хүнс"],
  },
  {
    keyWords: ["будаа"],
    catalog: ["Үр тариа"],
    updatedAt: { _seconds: 1627213871, _nanoseconds: 986000000 },
    id: "SjGvvoLH9lsITCvZSYHL",
    available: true,
    images: ["https://cdn.geresee.tk/ur_taria/хималайн ягаан давс 1.jpg"],
    size: "1ш",
    price: "6000",
    name: "Хималайн ягаан давс 1",
  },
  {
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/orange.jpg"],
    price: "9060",
    catalog: ["Жимс жимсгэнэ"],
    keyWords: ["fruit"],
    size: "1kg",
    available: true,
    updatedAt: { _seconds: 1627213869, _nanoseconds: 940000000 },
    name: "оранж",
    id: "SnGPYiPX7Qq92ePRT8y8",
  },
  {
    available: true,
    updatedAt: { _nanoseconds: 903000000, _seconds: 1627213946 },
    catalog: ["Тамхи"],
    id: "SvosPLckQanHoJb2HMEM",
    name: "Esse blue тамхи",
    keyWords: ["tobacco"],
    price: "4400",
    size: "1",
    images: ["https://cdn.geresee.tk/cigarettes/esse_blue.jpg"],
  },
  {
    price: "6600",
    updatedAt: { _seconds: 1627213915, _nanoseconds: 105000000 },
    size: "1ш",
    available: true,
    images: ["https://cdn.geresee.tk/Амттан/Шоколадан үрэл.jpg"],
    catalog: ["Амттан"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    name: "Шоколадан үрэл",
    id: "T4VpdvP3N5edaZK6Ul0W",
  },
  {
    catalog: ["Цай, кофе"],
    name: "Зөгийн бал 2",
    images: ["https://cdn.geresee.tk/tea_coffee/зөгийн бал 2.jpg"],
    price: "25000",
    size: "1ш",
    keyWords: [],
    id: "T7rEGIgpHLLmrQL5SQye",
    available: true,
    updatedAt: { _seconds: 1627213944, _nanoseconds: 273000000 },
  },
  {
    available: true,
    images: ["https://cdn.geresee.tk/cigarettes/tamhi_bohem.jpg"],
    keyWords: ["tobacco"],
    updatedAt: { _seconds: 1627214030, _nanoseconds: 846000000 },
    price: "4780",
    size: "1",
    name: "BOHEM тамхи",
    id: "TAmKOSFIvYbug6Qf8YNM",
    catalog: ["Тамхи"],
  },
  {
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Майонез.jpg"],
    id: "TEuoSI3Xb7F0nyXhVhSz",
    name: "Майонез",
    updatedAt: { _nanoseconds: 867000000, _seconds: 1627213903 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    price: "8000",
    size: "1ш",
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    catalog: ["Шингэн хүнс"],
    name: "golden plum",
    price: "",
    updatedAt: { _nanoseconds: 367000000, _seconds: 1627213864 },
    available: true,
    size: "",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    id: "TO5MObIQx6CKD5GlVXPK",
    images: ["https://cdn.geresee.tk/us_undaa/golden_plum.jpg"],
  },
  {
    name: "Бэлэн гоймон мөөгтэй-чанадаг(Nongshim)",
    catalog: ["Нөөшилсөн хүнс"],
    available: true,
    id: "TX9IfMRh4AVM7pbR8XOS",
    price: "2000",
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон мөөгтэй-чанадаг(Nongshim).jpg",
    ],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    updatedAt: { _seconds: 1627214035, _nanoseconds: 888000000 },
    size: "1ш",
  },
  {
    updatedAt: { _seconds: 1627213927, _nanoseconds: 932000000 },
    id: "TyubHNNyEjNSruMFtkvT",
    catalog: ["Шингэн хүнс"],
    size: "0.5л",
    available: true,
    name: "mountain dev жижиг",
    images: ["https://cdn.geresee.tk/us_undaa/mountain_dev_light.jpg"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "1600",
  },
  {
    size: "1ш",
    updatedAt: { _nanoseconds: 49000000, _seconds: 1627214045 },
    price: "10000",
    id: "TzUUm6ZsLiMThD3fhouy",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Боловсруулсан хүнс"],
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Сыр-President.jpg"],
    available: true,
    name: "Сыр-President",
  },
  {
    updatedAt: { _nanoseconds: 31000000, _seconds: 1627213946 },
    price: "10000",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    catalog: ["Боловсруулсан хүнс"],
    name: "Масло-President",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Масло-President.jpg"],
    id: "U9BH4QtektOJwZGBbPuc",
    size: "1ш",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "Бүлгүги соус (гахайн)2",
    id: "UBPKQG03f4ivWs5Q43YC",
    available: true,
    updatedAt: { _seconds: 1627213868, _nanoseconds: 610000000 },
    size: "1ш",
    price: "8000",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/бүлгүги соус (гахайн)1(1).jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    available: true,
    price: "50000",
    id: "UGXT9vsWlpQ6HW43Q7x1",
    updatedAt: { _nanoseconds: 664000000, _seconds: 1627213949 },
    name: "мэрси том 2",
    size: "1ш",
    images: ["https://cdn.geresee.tk/Амттан/мэрси том 2.jpg"],
    catalog: ["Амттан"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
  },
  {
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /taliin-mongol-honi-kaltstai-buuz.jpg",
    ],
    updatedAt: { _seconds: 1627213857, _nanoseconds: 561000000 },
    catalog: ["Мах махан бүтээгдэхүүн"],
    name: "Талын монгол кальцтай бууз",
    id: "UK663SFlAqEbfwqSw0Ud",
    price: "9000",
    keyWords: [],
    available: true,
    size: "900г",
  },
  {
    size: "1ш",
    updatedAt: { _seconds: 1627213897, _nanoseconds: 33000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "8000",
    catalog: ["Боловсруулсан хүнс"],
    id: "V5bonrcg0Hw4Rgohq1uu",
    available: true,
    name: "Дарсан өгөрций 920гр",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/Дарсан өгөрций 920гр.jpg",
    ],
  },
  {
    updatedAt: { _nanoseconds: 837000000, _seconds: 1627213920 },
    available: true,
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон(Nongshim).jpg",
    ],
    price: "1500",
    name: "Бэлэн гоймон(Nongshim)",
    id: "VQg55nje4LyKOzthLzQb",
    catalog: ["Нөөшилсөн хүнс"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    size: "1ш",
  },
  {
    available: true,
    updatedAt: { _nanoseconds: 673000000, _seconds: 1627213858 },
    size: "450г",
    keyWords: [],
    price: "6000",
    catalog: ["Мах махан бүтээгдэхүүн"],
    name: "Бяслагтай котлет",
    id: "VVT83rWTfpNsnGk9ZxbE",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /zochin-buuz-byslagtai-kotlet.jpg",
    ],
  },
  {
    id: "VyRoe1VF0w5LS8oDFLYL",
    updatedAt: { _seconds: 1627214033, _nanoseconds: 881000000 },
    name: "Халуун ногоотой чихэрлэг чили соус том",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "1ш",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/халуун ногоотой чихэрлэг чили соус том.jpg",
    ],
    price: "5500",
    catalog: ["Боловсруулсан хүнс"],
    available: true,
  },
  {
    catalog: ["Тамхи"],
    price: "4780",
    keyWords: ["tobacco"],
    name: "BOHEM no_6 тамхи",
    images: ["https://cdn.geresee.tk/cigarettes/tamhi_bohem_no_6.jpg"],
    available: true,
    id: "W1M0ahLPVhOSVHda5DEp",
    size: "1",
    updatedAt: { _seconds: 1627213974, _nanoseconds: 657000000 },
  },
  {
    size: "1ш",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    id: "W38LchGmC1J25DMhhgCX",
    available: true,
    catalog: ["Амттан"],
    name: "Раффаэлло2",
    updatedAt: { _nanoseconds: 458000000, _seconds: 1627213892 },
    images: ["https://cdn.geresee.tk/Амттан/Раффаэлло2.jpg"],
    price: "10000",
  },
  {
    updatedAt: { _seconds: 1627213984, _nanoseconds: 962000000 },
    price: "3750",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "hartweizen гоймон",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/hartweizen_goimon.jpg",
    ],
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    id: "WCASS5E8aihQAwK39XSk",
    size: "500гр",
    available: true,
  },
  {
    available: true,
    catalog: ["Аxуйн хэрэглээ"],
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    id: "WED9IQaHaNOEorb1CVqU",
    size: "24ш",
    updatedAt: { _seconds: 1627213950, _nanoseconds: 553000000 },
    price: "20000",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/Huggies_H.jpg"],
    name: "Huggies M",
  },
  {
    keyWords: ["tobacco"],
    size: "1",
    catalog: ["Тамхи"],
    price: "4400",
    images: ["https://cdn.geresee.tk/cigarettes/esse_change.jpg"],
    available: true,
    name: "Esse change тамхи",
    id: "Wg6V00J6L9Yny0C7uGNo",
    updatedAt: { _seconds: 1627213926, _nanoseconds: 962000000 },
  },
  {
    images:
      "https://firebasestorage.googleapis.com/v0/b/crawler-ef1f1.appspot.com/o/products%2FupdatedImages%2FIMG_3378.JPG?alt=media&token=540c799c-7144-41d2-a8e9-cae6696065fb",
    available: false,
    size: "",
    price: "32323",
    catalog: ["Архи, Пиво"],
    name: "өйыолрөб",
    createdAt: { _seconds: 1637051213, _nanoseconds: 10000000 },
  },
  {
    id: "XPm93qb8ghPUvxI5gbUh",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    catalog: ["Амттан"],
    available: true,
    price: "6200",
    size: "1ш",
    images: ["https://cdn.geresee.tk/Амттан/Тоффифээ1.jpg"],
    updatedAt: { _nanoseconds: 795000000, _seconds: 1627214022 },
    name: "Тоффифээ1",
  },
  {
    size: "4ш",
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    price: "6000",
    name: "selpak super soft ариун цэврийн цаас",
    updatedAt: { _seconds: 1627213937, _nanoseconds: 158000000 },
    id: "XsbM9x29rNVOHT12gduM",
    catalog: ["Аxуйн хэрэглээ"],
    images: ["https://cdn.geresee.tk/ahuin_hereglee/selpak_super_soft.jpg"],
    available: true,
  },
  {
    keyWords: [],
    name: "Мөнхийн болор зочин хиам",
    price: "7000",
    id: "Y8ff5nVyELdSVkqlifGb",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /munkhiin-bolor-zochin-hiam.jpg",
    ],
    updatedAt: { _nanoseconds: 593000000, _seconds: 1627213852 },
    size: "450г",
    catalog: ["Мах махан бүтээгдэхүүн"],
    available: true,
  },
  {
    name: "Оргио тахианий утсан цээжний мах",
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /orgio-tahianii-utsan-tseejnii-mah.jpg",
    ],
    id: "YGA6FUG0BlV9Dvnb6W4o",
    keyWords: [],
    size: "350г",
    updatedAt: { _seconds: 1627213854, _nanoseconds: 530000000 },
    available: true,
    catalog: ["Мах махан бүтээгдэхүүн"],
    price: "7000",
  },
  {
    updatedAt: { _seconds: 1627213904, _nanoseconds: 616000000 },
    catalog: ["Цай, кофе"],
    size: "230г",
    keyWords: [],
    images: ["https://cdn.geresee.tk/tea_coffee/jacobs_coffee_tom.jpg"],
    available: true,
    id: "YN08kVHUHwNlTlT8oJwA",
    price: "30000",
    name: "Jacobs кофе том",
  },
  {
    available: true,
    name: "Nescafe кофе gold",
    size: "95г",
    catalog: ["Цай, кофе"],
    id: "YZOQ09P36BoMJtAkdsCB",
    keyWords: [],
    price: "14460",
    updatedAt: { _nanoseconds: 810000000, _seconds: 1627214021 },
    images: ["https://cdn.geresee.tk/tea_coffee/nescafe_coffee_gold.jpg"],
  },
  {
    images: ["https://cdn.geresee.tk/Амттан/раффаэлo.jpg"],
    name: "Раффаэллo3",
    price: "3960",
    id: "YgVQ9LlPHrHT0pTlhZ7g",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    size: "1ш",
    catalog: ["Амттан"],
    available: true,
    updatedAt: { _seconds: 1627213908, _nanoseconds: 596000000 },
  },
  {
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    size: "80ш",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/kleenex.jpg"],
    updatedAt: { _seconds: 1627213978, _nanoseconds: 396000000 },
    available: true,
    name: "kleenex нойтон салфетка ",
    catalog: ["Аxуйн хэрэглээ"],
    id: "ZCmLpqQAdmbv9Sbpvtsi",
    price: "5280",
  },
  {
    updatedAt: { _seconds: 1627213862, _nanoseconds: 429000000 },
    id: "ZFvNN3HApn2U3tfdJcol",
    images: ["https://cdn.geresee.tk/ur_taria/sakura_budaa.jpg"],
    keyWords: ["будаа"],
    catalog: ["Үр тариа"],
    name: "сакура будаа",
    available: true,
    price: "14400",
    size: "1кг",
  },
  {
    keyWords: ["будаа"],
    price: "3350",
    updatedAt: { _seconds: 1627213971, _nanoseconds: 892000000 },
    id: "ZSHqmMsndjrNQ6W1S2s8",
    name: "слава шар будаа",
    available: true,
    size: "1kg",
    images: ["https://cdn.geresee.tk/ur_taria/slava_shar_budaa.jpg"],
    catalog: ["Үр тариа"],
  },
  {
    catalog: ["Амттан"],
    images: ["https://cdn.geresee.tk/Амттан/Сникерс.jpg"],
    updatedAt: { _nanoseconds: 899000000, _seconds: 1627213888 },
    id: "Zfbkraor3WlDBP1VLMUC",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    available: true,
    size: "1ш",
    price: "5400",
    name: "Сникерс",
  },
  {
    id: "aLdEt0aXpoedgjTCMRur",
    updatedAt: { _seconds: 1627213987, _nanoseconds: 810000000 },
    size: "1ш",
    available: true,
    images: ["https://cdn.geresee.tk/Амттан/Алфен голд.jpg"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    catalog: ["Амттан"],
    price: "2000",
    name: "Алфен голд",
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/lavsha_tuuzan_goimon_bortstoi.jpg",
    ],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _nanoseconds: 137000000, _seconds: 1627213945 },
    name: "лавша туузан гоймон борцтой ",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    price: "1280",
    id: "aQXqOTkjQh73E279HGZH",
    size: "300гр",
    available: true,
  },
  {
    available: true,
    images: ["https://cdn.geresee.tk/tea_coffee/Зөгийн бал1.jpg"],
    catalog: ["Цай, кофе"],
    updatedAt: { _seconds: 1627213957, _nanoseconds: 850000000 },
    price: "34000",
    id: "bCESuO0P8LrEk0tbrhbK",
    size: "1ш",
    keyWords: [],
    name: "Зөгийн бал1",
  },
  {
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    size: "2л",
    updatedAt: { _nanoseconds: 914000000, _seconds: 1627214036 },
    name: "дээж тараг элсэн чихэргүй",
    keyWords: ["сүү", "тараг", "аарц"],
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/deej_tarag_chihergui.jpg",
    ],
    id: "bFSkSPw2unkXbpMfR7R6",
    price: "2300",
    available: true,
  },
  {
    id: "bUpWGwaWnSa06y3XeWvO",
    available: true,
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/оливын тос.jpg"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "Оливын тос",
    size: "1ш",
    price: "31000",
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _nanoseconds: 141000000, _seconds: 1627213861 },
  },
  {
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/золотой майонез.jpg"],
    name: "Золотой майонез",
    price: "4610",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    id: "boXR1Cph6NDYsoLalDBt",
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213868, _nanoseconds: 148000000 },
    available: true,
    size: "1ш",
  },
  {
    size: "1ш",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    price: "2100",
    images: ["https://cdn.geresee.tk/Амттан/Харибо.jpg"],
    catalog: ["Амттан"],
    id: "cWhFAzGAkUz15tQWCOky",
    updatedAt: { _seconds: 1627213920, _nanoseconds: 18000000 },
    available: true,
    name: "Харибо",
  },
  {
    available: true,
    name: "Мэвьюс",
    price: "3960",
    images: ["https://cdn.geresee.tk/cigarettes/Мэвьюс.jpg"],
    catalog: ["Тамхи"],
    id: "cbDTEISorj31ArMwqtT5",
    updatedAt: { _seconds: 1627213966, _nanoseconds: 176000000 },
    size: "1ш",
    keyWords: ["tobacco"],
  },
  {
    price: "18290",
    available: true,
    size: "20ш",
    name: "Huggies L",
    catalog: ["Аxуйн хэрэглээ"],
    updatedAt: { _nanoseconds: 404000000, _seconds: 1627213935 },
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    id: "cgBeSMorbvbj45JQksXV",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/Huggies_L.jpg"],
  },
  {
    id: "ckfPKCjJumxewpzSivNT",
    updatedAt: { _nanoseconds: 954000000, _seconds: 1627214037 },
    catalog: ["Цай, кофе"],
    keyWords: [],
    name: "Зөгийн бал",
    images: ["https://cdn.geresee.tk/tea_coffee/Зөгийн бал.jpg"],
    price: "34000",
    size: "1ш",
    available: true,
  },
  {
    keyWords: ["шар айраг", "дарс", "вино", "согтууруулах ундаа"],
    price: "28130",
    id: "d4CSb0IBXUyzcLRQQcD2",
    available: true,
    name: "yellow tail chardonnay",
    size: "750мл",
    images: ["https://cdn.geresee.tk/vine%26beer/yellow_tail_chardonnay.jpg"],
    catalog: ["Архи, Пиво"],
    updatedAt: { _seconds: 1627213891, _nanoseconds: 679000000 },
  },
  {
    price: "2300",
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    updatedAt: { _nanoseconds: 202000000, _seconds: 1627213954 },
    id: "dIXw3yCqBEbHHnv1fRG7",
    keyWords: ["сүү", "тараг", "аарц"],
    available: true,
    name: "элгэн тараг",
    images: ["https://cdn.geresee.tk/Milk_and_milk_products/elgen_tarag.jpg"],
    size: "2л",
  },
  {
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /slava-gahain-mah.jpg",
    ],
    id: "dTQg1ncXKirA0Dty8H0j",
    catalog: ["Мах махан бүтээгдэхүүн"],
    updatedAt: { _seconds: 1627213855, _nanoseconds: 874000000 },
    available: true,
    size: "500г",
    price: "19800",
    name: "Слава гахайн мах",
    keyWords: [],
  },
  {
    keyWords: [],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /slava-tahian-tseejnii-mah-front.jpg",
    ],
    updatedAt: { _seconds: 1627213856, _nanoseconds: 896000000 },
    size: "1кг",
    price: "6160",
    catalog: ["Мах махан бүтээгдэхүүн"],
    id: "di2sfIkVbkIzrxeE8r8g",
    name: "Слава тахианий цээж мах",
    available: true,
  },
  {
    id: "dkM4CUto7ZMKzZ0oiZiN",
    updatedAt: { _nanoseconds: 494000000, _seconds: 1627213922 },
    keyWords: ["будаа"],
    size: "1ш",
    images: ["https://cdn.geresee.tk/ur_taria/бор сахар.jpg"],
    catalog: ["Үр тариа"],
    price: "7000",
    name: "Бор сахар",
    available: true,
  },
  {
    id: "doZ7yaY8pbMtvWyQ4C8T",
    name: "Хужирт цэвэр ус дунд",
    catalog: ["Шингэн хүнс"],
    updatedAt: { _nanoseconds: 922000000, _seconds: 1627213985 },
    size: "0.5л",
    images: ["https://cdn.geresee.tk/us_undaa/hujirt_dund.jpg"],
    available: true,
    price: "1410",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
  },
  {
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "500",
    id: "drSHiE6exrfsFNRTeLtP",
    size: "0.5л",
    available: true,
    catalog: ["Шингэн хүнс"],
    updatedAt: { _nanoseconds: 778000000, _seconds: 1627213932 },
    images: ["https://cdn.geresee.tk/us_undaa/bonaqua.jpg"],
    name: "bonaqua ус",
  },
  {
    updatedAt: { _nanoseconds: 38000000, _seconds: 1627213926 },
    catalog: ["Тамхи"],
    images: ["https://cdn.geresee.tk/cigarettes/Парламент крүес.jpg"],
    id: "dx2Hav2JNsNNW3GPZ5e8",
    keyWords: ["tobacco"],
    name: "Парламент крүес",
    price: "3960",
    available: true,
    size: "1ш",
  },
  {
    catalog: ["Тамхи"],
    images: ["https://cdn.geresee.tk/cigarettes/tamhi_marlboro.jpg"],
    updatedAt: { _seconds: 1627214004, _nanoseconds: 208000000 },
    keyWords: ["tobacco"],
    price: "4180",
    id: "e1BEeBLqVcAEIr2ywfBT",
    size: "1",
    name: "Marlboro тамхи",
    available: true,
  },
  {
    name: "Давс",
    images: ["https://cdn.geresee.tk/ur_taria/давс.jpg"],
    catalog: ["Үр тариа"],
    keyWords: ["будаа"],
    size: "1ш",
    id: "e3sd9IuTxvts63R2dh96",
    available: true,
    updatedAt: { _nanoseconds: 971000000, _seconds: 1627214012 },
    price: "1400",
  },
  {
    id: "elxFeWNXeXqOYTIIGKXE",
    size: "4ш",
    price: "6000",
    updatedAt: { _nanoseconds: 736000000, _seconds: 1627213973 },
    available: true,
    catalog: ["Аxуйн хэрэглээ"],
    name: "ариун цаасан алчуур",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/aruin.jpg"],
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
  },
  {
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    price: "2300",
    size: "2л",
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/aktivie_guizeelzgne.jpg",
    ],
    updatedAt: { _seconds: 1627213919, _nanoseconds: 169000000 },
    id: "eq6161TsZo1LVG4gtEc1",
    keyWords: ["сүү", "тараг", "аарц"],
    available: true,
    name: "активия тараг",
  },
  {
    price: "10000",
    id: "f0VmiVKuWCKG3HUuIMGC",
    size: "1ш",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _nanoseconds: 328000000, _seconds: 1627213964 },
    available: true,
    name: "Сыр1-President",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Сыр1-President.jpg"],
  },
  {
    catalog: ["Тамхи"],
    price: "4500",
    name: "MEVIUS sky blue тамхи",
    available: true,
    keyWords: ["tobacco"],
    id: "f1IUGXQTPcybE1spx44N",
    images: ["https://cdn.geresee.tk/cigarettes/tamhi_mevius_sky_blue.jpg"],
    updatedAt: { _nanoseconds: 92000000, _seconds: 1627214007 },
    size: "1",
  },
  {
    name: "punch",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    updatedAt: { _seconds: 1638167386, _nanoseconds: 680000000 },
    price: "1022",
    size: "0.5л",
    images:
      "https://firebasestorage.googleapis.com/v0/b/nest-shopping-app.appspot.com/o/products%2Fus_undaa%2Flaimon_orange.jpg?alt=media&token=a94ac151-d534-4f5b-93ae-4cf2be4102dd",
    id: "f7vedEaOzSW5wnscyatC",
    catalog: ["Шингэн хүнс"],
    available: "Байхгүй",
  },
  {
    name: "Доритос-том(taco)",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Доритос-том(taco).jpg"],
    updatedAt: { _seconds: 1627214025, _nanoseconds: 799000000 },
    catalog: ["Нөөшилсөн хүнс"],
    id: "fPunZChgersAvxyboNxX",
    size: "1ш",
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    available: true,
    price: "3800",
  },
  {
    catalog: ["Шингэн хүнс"],
    name: "нимбэгний спрайт том",
    id: "fWSvE9VF7c49w1igLfyI",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/lemon_sprite_big.jpg"],
    available: true,
    updatedAt: { _seconds: 1627213862, _nanoseconds: 93000000 },
    size: "2л",
    price: "3420",
  },
  {
    name: "Лайс-Краб",
    id: "fpAFeoqU3SzoZpKizBYQ",
    size: "1ш",
    updatedAt: { _seconds: 1627214039, _nanoseconds: 967000000 },
    price: "3800",
    catalog: ["Нөөшилсөн хүнс"],
    available: true,
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Лайс-Краб.jpg"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
  },
  {
    available: true,
    catalog: ["Мах махан бүтээгдэхүүн"],
    id: "g8uoPF9iN6uSSfZYEACg",
    keyWords: [],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /taliin-mongol-honi-zorson-mah-front.jpg.jpg",
    ],
    price: "3850",
    name: "Талын монгол хонины зорсон мах",
    updatedAt: { _seconds: 1627213858, _nanoseconds: 116000000 },
    size: "300г",
  },
  {
    price: "1700",
    name: "гүзээлзгэнэ липтон",
    catalog: ["Шингэн хүнс"],
    id: "glEobqwTlwY64QTY3SE1",
    updatedAt: { _nanoseconds: 479000000, _seconds: 1627213977 },
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/strawberry_lipton.jpg"],
    size: "0.5л",
  },
  {
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2500",
    images: ["https://cdn.geresee.tk/us_undaa/black_mineral.jpg"],
    name: "black mineral ус",
    available: true,
    size: "0.5л",
    catalog: ["Шингэн хүнс"],
    id: "gmvKtvK8drX93iJuEPHO",
    updatedAt: { _nanoseconds: 807000000, _seconds: 1627213900 },
  },
  {
    price: "6900",
    updatedAt: { _nanoseconds: 770000000, _seconds: 1627213864 },
    id: "h1MHcZoiySw2vnBIGlA6",
    available: true,
    name: "Ногооны салад",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Ногооны салад.jpg"],
    size: "1ш",
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    size: "1ш",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Кимчи-400гр.jpg"],
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213866, _nanoseconds: 874000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    id: "h7TMOOoEZcholalN2W5A",
    price: "3000",
    available: true,
    name: "Кимчи-400гр",
  },
  {
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _nanoseconds: 903000000, _seconds: 1627213882 },
    available: true,
    price: "12000",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "хунчиртай банш",
    id: "h7VVtjKX6EHwi639HBnG",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/hunchirtai_bansh.jpg"],
    size: "800г",
  },
  {
    available: true,
    price: "1000",
    images: ["https://cdn.geresee.tk/us_undaa/bonaqua_dund.jpg"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "bonaqua ус дунд",
    id: "h9iW2pDOY0fW2njOFhJ3",
    size: "1л",
    catalog: ["Шингэн хүнс"],
    updatedAt: { _nanoseconds: 248000000, _seconds: 1627214001 },
  },
  {
    keyWords: [],
    name: "Малчин хагас утлагат хиам",
    available: true,
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /malchin-hagas-utalgat-hiam.jpg",
    ],
    updatedAt: { _seconds: 1627213852, _nanoseconds: 316000000 },
    size: "450г",
    id: "hQL071G4T7valhRk57Ac",
    catalog: ["Мах махан бүтээгдэхүүн"],
    price: "6000",
  },
  {
    price: "4500",
    catalog: ["Шингэн хүнс"],
    size: "1.5л",
    id: "hQwuhsPZqsqvl0OYN4JB",
    updatedAt: { _nanoseconds: 844000000, _seconds: 1627214019 },
    images: ["https://cdn.geresee.tk/us_undaa/laimon_cola_tom.jpg"],
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "laimon кола том",
  },
  {
    catalog: ["Мах махан бүтээгдэхүүн"],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /orgio-tseejnii-mah-front.jpg",
    ],
    updatedAt: { _seconds: 1627213854, _nanoseconds: 989000000 },
    size: "850г",
    keyWords: [],
    id: "hvzWF2iA4e5jcl2vFQno",
    available: true,
    price: "6000",
    name: "Оргио тахианий цээж мах",
  },
  {
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/Улаанбаатар майонез.jpg",
    ],
    id: "iTntWDxmEPuwbPQJPzKu",
    size: "1ш",
    available: true,
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213997, _nanoseconds: 375000000 },
    price: "6350",
    name: "Улаанбаатар майонез",
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    size: "1ш",
    available: true,
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон чанадаг(Nongshim).jpg",
    ],
    name: "Бэлэн гоймон чанадаг(Nongshim)",
    id: "jXQjCS6ax6KhBIKznhB7",
    catalog: ["Нөөшилсөн хүнс"],
    updatedAt: { _seconds: 1627213998, _nanoseconds: 455000000 },
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "2000",
  },
  {
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    images: ["https://cdn.geresee.tk/Milk_and_milk_products/deej_suu.jpg"],
    updatedAt: { _seconds: 1627213880, _nanoseconds: 745000000 },
    size: "2л",
    price: "2300",
    name: "дээж сүү",
    keyWords: ["сүү", "тараг", "аарц"],
    id: "jbwO8XOgmIJNp0wLqNQz",
    available: true,
  },
  {
    name: "төмс",
    keyWords: [],
    id: "jcewBFqKsYY3Ou03T20B",
    available: true,
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/toms_tom.jpg"],
    price: "4000",
    catalog: ["Хүнсний ногоо"],
    size: "3кг",
    updatedAt: { _nanoseconds: 37000000, _seconds: 1627213968 },
  },
  {
    price: "0.5кг",
    keyWords: [],
    size: "0.5кг",
    name: "сонгино",
    id: "jf2SKdduORfD66xaKb1l",
    updatedAt: { _seconds: 1627213886, _nanoseconds: 220000000 },
    catalog: ["Хүнсний ногоо"],
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/songino.jpg"],
    available: true,
  },
  {
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/amtlag_tarag_guzeelzgne.jpg",
    ],
    updatedAt: { _seconds: 1627213924, _nanoseconds: 149000000 },
    keyWords: ["сүү", "тараг", "аарц"],
    available: true,
    size: "2л",
    name: "амтлаг тараг гүзээлзгэнэтэй",
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    price: "2300",
    id: "jjdcbycbXBkV22mOFzvx",
  },
  {
    updatedAt: { _nanoseconds: 221000000, _seconds: 1627213878 },
    catalog: ["Нөөшилсөн хүнс"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    name: "Бэлэн гоймон мөөгтэй-жижиг(Jin Ramen)",
    available: true,
    id: "jpdtzPzQd51tW81hAxfp",
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон мөөгтэй-жижиг(Jin Ramen).jpg",
    ],
    price: "1500",
    size: "1ш",
  },
  {
    name: "Нийслэл бүтэн утлагат хиам",
    updatedAt: { _seconds: 1627213852, _nanoseconds: 872000000 },
    size: "450г",
    keyWords: [],
    catalog: ["Нөөшилсөн хүнс"],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /niislel-buten-utalgat-hiam.jpg",
    ],
    price: "8030",
    available: true,
    id: "jwt4K0S7JHjPCSvxbpgf",
  },
  {
    available: true,
    updatedAt: { _nanoseconds: 586000000, _seconds: 1627213889 },
    name: "Huggies XL",
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    size: "20ш",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/Huggies_XL.jpg"],
    catalog: ["Нөөшилсөн хүнс"],
    id: "k93MgYEhCBGo8YKfRPjF",
    price: "20000",
  },
  {
    id: "kIkcQ6CT5vu2MYilmhsl",
    name: "Бүлгүги соус (үхрийн) 2",
    size: "1ш",
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _nanoseconds: 202000000, _seconds: 1627213893 },
    price: "8000",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/бүлгүги соус (үхрийн) 2.jpg",
    ],
    available: true,
  },
  {
    size: "2л",
    updatedAt: { _nanoseconds: 141000000, _seconds: 1627213982 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/zero_pepsi_big.jpg"],
    available: true,
    id: "kTrSCXqGoWUKgtkLvxFF",
    name: "zero пепси том",
    price: "3500",
  },
  {
    images: ["https://cdn.geresee.tk/Амттан/М%26М-бор том.jpg"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    price: "8000",
    name: "М&М-бор том",
    id: "kWeMMlF4Nng93667cE92",
    available: true,
    updatedAt: { _seconds: 1627213913, _nanoseconds: 476000000 },
    catalog: ["Шингэн хүнс"],
    size: "1ш",
  },
  {
    price: "3000",
    id: "kfuS0NGPj0MqQRIJYhie",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/олейна.jpg"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "1ш",
    updatedAt: { _seconds: 1627213866, _nanoseconds: 451000000 },
    catalog: ["Боловсруулсан хүнс"],
    available: true,
    name: "Цөцгийн тос Олейна",
  },
  {
    updatedAt: { _nanoseconds: 799000000, _seconds: 1627213939 },
    size: "0.5л",
    images: ["https://cdn.geresee.tk/us_undaa/laimon_cola.jpg"],
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2060",
    id: "kuXpp8DODApGfB7dX8r4",
    name: "laimon кола",
    catalog: ["Шингэн хүнс"],
  },
  {
    available: false,
    size: "",
    name: "fds",
    catalog: [],
    price: "21",
    createdAt: { _seconds: 1637818452, _nanoseconds: 904000000 },
  },
  {
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/talh_ontsgoi_tsagaan.jpg",
    ],
    available: true,
    updatedAt: { _seconds: 1627213897, _nanoseconds: 771000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
    name: "талх онцгой цагаан",
    id: "lFkCf3Em9fR8T5SRD1Jc",
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    size: "1",
    price: "1810",
  },
  {
    name: "Халуун чинжүүний зуурмаг 2",
    price: "5500",
    available: true,
    size: "1ш",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/халуун чинжүүний зуурмаг 2.jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
    id: "lbb0iEHOm1io7y7QNgnU",
    updatedAt: { _seconds: 1627213940, _nanoseconds: 710000000 },
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    available: true,
    updatedAt: { _seconds: 1627213988, _nanoseconds: 765000000 },
    id: "m0IgZRAvkfXEeOXrSiKY",
    size: "1",
    catalog: ["Тамхи"],
    price: "4180",
    keyWords: ["tobacco"],
    name: "MEVIUS less smoke smell тамхи",
    images: [
      "https://cdn.geresee.tk/cigarettes/tamhi_mevius_less_smoke_smell.jpg",
    ],
  },
  {
    id: "mK5prKuGnMYN8SahdUPo",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2100",
    images: ["https://cdn.geresee.tk/us_undaa/bachus.jpg"],
    catalog: ["Шингэн хүнс"],
    available: true,
    size: "350л",
    updatedAt: { _nanoseconds: 445000000, _seconds: 1627213876 },
    name: "баккус",
  },
  {
    price: "4500",
    size: "1.5л",
    id: "nGZ4JfMQjiClYIikI8Xi",
    updatedAt: { _nanoseconds: 404000000, _seconds: 1627213859 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    available: true,
    catalog: ["Шингэн хүнс"],
    name: "laimon fresh том",
    images: ["https://cdn.geresee.tk/us_undaa/laimon_fresh_tom.jpg"],
  },
  {
    id: "nzHsqJdBff0YjVkFlRBB",
    price: "5000",
    name: "Карри (халуун ногоо бага)",
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _nanoseconds: 407000000, _seconds: 1627213963 },
    size: "1ш",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/карри (халуун ногоо бага  ).jpg",
    ],
    available: true,
  },
  {
    catalog: ["Шингэн хүнс"],
    available: true,
    updatedAt: { _seconds: 1627213860, _nanoseconds: 496000000 },
    price: "3000",
    images: ["https://cdn.geresee.tk/us_undaa/zero_cola_big.jpg"],
    size: "2л",
    id: "o7p39O36PsUJ1OAJqf0K",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "zero кола том",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "6000",
    size: "1ш",
    name: "Сэриал 1",
    updatedAt: { _seconds: 1627213979, _nanoseconds: 334000000 },
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/сэриал 1.jpg"],
    catalog: ["Боловсруулсан хүнс"],
    available: true,
    id: "oTsVKXzheqK1UeTHZHeC",
  },
  {
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    size: "4ш",
    updatedAt: { _nanoseconds: 448000000, _seconds: 1627213861 },
    catalog: ["Аxуйн хэрэглээ"],
    available: true,
    images: ["https://cdn.geresee.tk/ahuin_hereglee/selpak_perfumed.jpg"],
    price: "6320",
    id: "ofOMeukamtg1RDFPJeo8",
    name: "selpak perfumed ариун цэврийн цаас",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    updatedAt: { _nanoseconds: 254000000, _seconds: 1627213980 },
    price: "10000",
    size: "1ш",
    id: "owRrI90yu62GTlJJukB2",
    available: true,
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Сыр-Hochland.jpg"],
    catalog: ["Боловсруулсан хүнс"],
    name: "Сыр-Hochland",
  },
  {
    keyWords: ["будаа"],
    name: "Хималайн ягаан давс 2",
    id: "owwlFftHHfEauPdJQQZP",
    size: "1ш",
    price: "6000",
    catalog: ["Үр тариа"],
    images: ["https://cdn.geresee.tk/ur_taria/хималайн ягаан давс 2.jpg"],
    updatedAt: { _nanoseconds: 810000000, _seconds: 1627213972 },
    available: true,
  },
  {
    available: true,
    catalog: ["Амттан"],
    updatedAt: { _seconds: 1627213991, _nanoseconds: 616000000 },
    size: "1ш",
    id: "pEdGGU8jeU91ohVefW8X",
    name: "Озэра",
    price: "3000",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    images: ["https://cdn.geresee.tk/Амттан/Озэра.jpg"],
  },
  {
    size: "1ш",
    updatedAt: { _seconds: 1627214040, _nanoseconds: 982000000 },
    catalog: ["Нөөшилсөн хүнс"],
    available: true,
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон мөөгтэй(Jin ramen).jpg",
    ],
    id: "ptE07RkDiED1fnnrPH2y",
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "2500",
    name: "Бэлэн гоймон мөөгтэй(Jin ramen)",
  },
  {
    images: ["https://cdn.geresee.tk/ur_taria/slava_elsen_chiher.jpg"],
    catalog: ["Нөөшилсөн хүнс", "test"],
    id: "pvAN3wYCeyycSWKiudvv",
    size: "2л",
    name: "mountain dev том",
    available: "Байхгүй",
    keyWords: ["будаа"],
    updatedAt: { _seconds: 1638260505, _nanoseconds: 263000000 },
    price: "3480",
  },
  {
    keyWords: ["tobacco"],
    size: "1ш",
    catalog: ["Тамхи"],
    price: "3960",
    id: "pwrbSyV8g48bIXFmdFCU",
    updatedAt: { _nanoseconds: 846000000, _seconds: 1627214028 },
    name: "Парламент ocean cruise",
    images: ["https://cdn.geresee.tk/cigarettes/Парламент ocean cruise.jpg"],
    available: true,
  },
  {
    keyWords: ["будаа"],
    catalog: ["Үр тариа"],
    available: true,
    images: ["https://cdn.geresee.tk/ur_taria/slava_tsagaan_budaa_tom.jpg"],
    size: "2кг",
    price: "8000",
    name: "слава цагаан будаа том",
    id: "qnNjEBm6CPeKWVIy1Ay9",
    updatedAt: { _seconds: 1627213860, _nanoseconds: 161000000 },
  },
  {
    images: ["https://cdn.geresee.tk/Milk_and_milk_products/sain_tarag.jpg"],
    updatedAt: { _seconds: 1627213902, _nanoseconds: 317000000 },
    available: true,
    keyWords: ["сүү", "тараг", "аарц"],
    id: "qplbxMgxXut2DMWHTGZg",
    price: "2300",
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    name: "сайн тараг",
    size: "2л",
  },
  {
    catalog: ["Шингэн хүнс"],
    price: "2100",
    id: "r3GWpoSVRwQehclSWF5P",
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    images: ["https://cdn.geresee.tk/us_undaa/bacchus.jpg"],
    updatedAt: { _nanoseconds: 516000000, _seconds: 1627213872 },
    available: true,
    size: "350л",
    name: "баккус цэнхэр",
  },
  {
    updatedAt: { _nanoseconds: 16000000, _seconds: 1627213956 },
    images: ["https://cdn.geresee.tk/Амттан/Үзэм.jpg"],
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    id: "rJ90qzS8ixogjoFA97Rz",
    price: "20000",
    size: "1ш",
    catalog: ["Амттан"],
    available: true,
    name: "Үзэм",
  },
  {
    size: "1ш",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    id: "s9bXZmg3g1s5ZYpprtkW",
    images: ["https://cdn.geresee.tk/Амттан/М%26М бор.jpg"],
    catalog: ["Амттан"],
    available: true,
    updatedAt: { _nanoseconds: 837000000, _seconds: 1627213931 },
    name: "М&М бор",
    price: "12800",
  },
  {
    updatedAt: { _seconds: 1627213996, _nanoseconds: 458000000 },
    available: true,
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    catalog: ["Нөөшилсөн хүнс"],
    size: "1ш",
    name: "Принглэс-Original",
    price: "3800",
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Принглэс-Original.jpg"],
    id: "sD4DW4K7DGBCkrz224RC",
  },
  {
    updatedAt: { _nanoseconds: 734000000, _seconds: 1627213916 },
    id: "sEhB1tLAGzamDKHF426c",
    catalog: ["Шингэн хүнс"],
    price: "1700",
    images: ["https://cdn.geresee.tk/us_undaa/multi_kagome.jpg"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    available: true,
    size: "0.5л",
    name: "мулти кагомэ",
  },
  {
    updatedAt: { _seconds: 1627213869, _nanoseconds: 33000000 },
    catalog: ["Нөөшилсөн хүнс"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    name: "Бэлэн гоймон-жижиг(Jin ramen)",
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон-жижиг(Jin ramen).jpg",
    ],
    id: "sRY6YDOZ0wEYZsBhtSo7",
    size: "1ш",
    price: "1500",
    available: true,
  },
  {
    images: ["https://cdn.geresee.tk/vine%26beer/JP_Chenet_Muscat.jpg"],
    available: true,
    size: "750мл",
    price: "26000",
    id: "sTuWQg4L9M2up8vos6aP",
    catalog: ["Архи, Пиво"],
    keyWords: ["шар айраг", "дарс", "вино", "согтууруулах ундаа"],
    updatedAt: { _nanoseconds: 441000000, _seconds: 1627213942 },
    name: "JP Chenet Muscat",
  },
  {
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "лаазалсан спрайт",
    catalog: ["Шингэн хүнс"],
    id: "soFOTEI3WGKNTLxoGGJ3",
    images: ["https://cdn.geresee.tk/us_undaa/sprite_can.jpg"],
    size: "350мл",
    price: "1900",
    available: true,
    updatedAt: { _nanoseconds: 851000000, _seconds: 1627214029 },
  },
  {
    available: true,
    price: "2200",
    size: "1kg",
    images: [
      "https://cdn.geresee.tk/Гурил%2C гурилан бүтээгдэхүүн/ulaanbaatar_guril_eruul_mend.jpg",
    ],
    updatedAt: { _seconds: 1627213880, _nanoseconds: 135000000 },
    name: "Улаанбаатар эрүүл мэндийн гурил",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    catalog: ["Гурил гурилан бүтээгдэхүүн"],
    id: "ssPwDF68Ai30bazXcFfe",
  },
  {
    size: "20ш",
    name: "элэг хамгаалах цай",
    images: ["https://cdn.geresee.tk/tea_coffee/eleg_hamgaalah_tsai.jpg"],
    updatedAt: { _nanoseconds: 217000000, _seconds: 1627214003 },
    available: true,
    catalog: ["Цай, кофе"],
    keyWords: [],
    price: "7440",
    id: "t16lbrLbYcz4wnSHo3V4",
  },
  {
    id: "tFG7e5881dtNiM2YbiAa",
    available: true,
    size: "0.5л",
    catalog: ["Шингэн хүнс"],
    updatedAt: { _nanoseconds: 103000000, _seconds: 1627213882 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "2500",
    name: "black balance ус",
    images: ["https://cdn.geresee.tk/us_undaa/black_balance.jpg"],
  },
  {
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/kalitsitai_buuz.jpg"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "900г",
    price: "12000",
    id: "tVNdhoLnc7fo3PvbKSPh",
    available: true,
    name: "кальцитай бууз",
    updatedAt: { _nanoseconds: 200000000, _seconds: 1627213884 },
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    size: "2л",
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/actimel_pomagranade_tarag.jpg",
    ],
    id: "tazwsfXMludvEZGDkrKi",
    name: "актимель помагэт тараг",
    updatedAt: { _seconds: 1627213965, _nanoseconds: 247000000 },
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    available: true,
    price: "2300",
    keyWords: ["сүү", "тараг", "аарц"],
  },
  {
    updatedAt: { _seconds: 1627213983, _nanoseconds: 70000000 },
    keyWords: ["tobacco"],
    available: true,
    size: "1",
    price: "4720",
    id: "tuX9T2EFrmKOmNAbEhIz",
    images: ["https://cdn.geresee.tk/cigarettes/tamhi_marlboro_gold.jpg"],
    name: "Marlboro Gold тамхи",
    catalog: ["Тамхи"],
  },
  {
    price: "1700",
    images: ["https://cdn.geresee.tk/us_undaa/lemon_lipton.jpg"],
    updatedAt: { _seconds: 1627214005, _nanoseconds: 158000000 },
    size: "0.5л",
    id: "tud6a1sr7vBsBfIAOVrR",
    catalog: ["Шингэн хүнс"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    name: "липтон Лимон",
    available: true,
  },
  {
    size: "1ш",
    name: "Дарсан өгөрций 680гр",
    updatedAt: { _nanoseconds: 419000000, _seconds: 1627213905 },
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/Дарсан өгөрций 680гр.jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
    id: "uHCkhqQhlHZsjowQasCm",
    available: true,
    price: "7000",
  },
  {
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    images: ["https://cdn.geresee.tk/Амттан/Твикс.jpg"],
    catalog: ["Амттан"],
    updatedAt: { _seconds: 1627213907, _nanoseconds: 798000000 },
    id: "uWk9ekCWAXXo32BThF6Z",
    size: "1ш",
    name: "Твикс",
    available: true,
    price: "5400",
  },
  {
    price: "2700",
    images: ["https://cdn.geresee.tk/ur_taria/slava_tsagaan_budaa_tom.jpg"],
    catalog: ["Үр тариа"],
    available: true,
    id: "uYzl7s6e6jqDscnDbLej",
    keyWords: ["будаа"],
    updatedAt: { _nanoseconds: 297000000, _seconds: 1627214000 },
    size: "650g",
    name: "слава цагаан будаа",
  },
  {
    id: "vRjB6dZVGkGgXX5vn55u",
    name: "том пепси",
    price: "3480",
    catalog: ["Шингэн хүнс"],
    size: "2л",
    images: ["https://cdn.geresee.tk/us_undaa/pepsi_big.jpg"],
    updatedAt: { _nanoseconds: 876000000, _seconds: 1627213884 },
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    available: true,
  },
  {
    catalog: ["Шингэн хүнс"],
    updatedAt: { _nanoseconds: 344000000, _seconds: 1627213943 },
    images: ["https://cdn.geresee.tk/us_undaa/seven_up_big.jpg"],
    size: "2л",
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    price: "3480",
    id: "vcSy9uk65ZV8f9WcdIWT",
    name: "seven up том",
  },
  {
    updatedAt: { _nanoseconds: 650000000, _seconds: 1627213959 },
    id: "veTS7GIekzHbksd8FO1R",
    size: "2kg",
    name: "байцай",
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/baitsaa.jpg"],
    keyWords: [],
    price: "6000",
    catalog: ["Хүнсний ногоо"],
    available: true,
  },
  {
    updatedAt: { _seconds: 1627214043, _nanoseconds: 20000000 },
    price: "4000",
    name: "Алимны нухаш",
    catalog: ["Боловсруулсан хүнс"],
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/алимны нухаш.jpg"],
    id: "wBdrRkciyuFyyhaMPjts",
    available: true,
    keyWords: ["гурил", "гоймон", "шпагетти"],
    size: "1ш",
  },
  {
    id: "wE0SHSuR46TrzrCow1bR",
    price: "8000",
    name: "Бүлгүги соус (гахайн)1",
    keyWords: ["гурил", "гоймон", "шпагетти"],
    available: true,
    size: "1ш",
    images: [
      "https://cdn.geresee.tk/Боловсруулсан хүнс/бүлгүги соус (гахайн)1.jpg",
    ],
    catalog: ["Боловсруулсан хүнс"],
    updatedAt: { _seconds: 1627213960, _nanoseconds: 633000000 },
  },
  {
    name: "лаазалсан фанта",
    size: "350мл",
    price: "1900",
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/grape_fanta_can.jpg"],
    id: "wXuFgAsteeT3Jb0amJt0",
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    updatedAt: { _nanoseconds: 59000000, _seconds: 1627214009 },
  },
  {
    images: ["https://cdn.geresee.tk/us_undaa/orange_kagome.jpg"],
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    updatedAt: { _nanoseconds: 53000000, _seconds: 1627213873 },
    available: true,
    size: "0.5л",
    price: "1700",
    id: "wYecCNgmedE0QuUfaNQE",
    name: "оранж кагомэ",
    catalog: ["Шингэн хүнс"],
  },
  {
    updatedAt: { _nanoseconds: 901000000, _seconds: 1627214014 },
    images: [
      "https://cdn.geresee.tk/Нөөшилсөн хүнс/Бэлэн гоймон мөөгтэй(Nongshim).jpg",
    ],
    available: true,
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    catalog: ["Нөөшилсөн хүнс"],
    id: "wgP1abv3D66BkvqfbMK4",
    price: "2500",
    name: "Бэлэн гоймон мөөгтэй(Nongshim)",
    size: "1ш",
  },
  {
    available: true,
    catalog: ["Цай, кофе"],
    name: "чихрийн шнжингийн цай",
    updatedAt: { _seconds: 1627213899, _nanoseconds: 316000000 },
    id: "wpntbJw1bcMKBVLLEkCM",
    images: ["https://cdn.geresee.tk/tea_coffee/chihriin_shijingiin_tsai.jpg"],
    price: "25000",
    keyWords: [],
    size: "20ш",
  },
  {
    keyWords: ["гурил", "гоймон", "шпагетти"],
    price: "5000",
    size: "1ш",
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Кимчи-900гр.jpg"],
    id: "xNrvi3Y22Bkm7PacqD2k",
    available: true,
    updatedAt: { _nanoseconds: 561000000, _seconds: 1627213885 },
    name: "Кимчи-900гр",
    catalog: ["Боловсруулсан хүнс"],
  },
  {
    images: ["https://cdn.geresee.tk/tea_coffee/bultsuut_tsetsgiin_tsai.jpg"],
    available: true,
    catalog: ["Цай, кофе"],
    keyWords: [],
    name: "булцуут цэцгийн цай",
    size: "20ш",
    price: "7440",
    id: "xcMaYla2fL2CG6Zu7fM4",
    updatedAt: { _seconds: 1627213881, _nanoseconds: 430000000 },
  },
  {
    keyWords: [],
    price: "10150",
    name: "Yellow label цай том",
    catalog: ["Цай, кофе"],
    available: true,
    size: "100ш",
    images: ["https://cdn.geresee.tk/tea_coffee/yellow_label_tom.jpg"],
    updatedAt: { _seconds: 1627213938, _nanoseconds: 46000000 },
    id: "xqrkji8bQEaYO4Lgq2KN",
  },
  {
    images: ["https://cdn.geresee.tk/Боловсруулсан хүнс/Компод-үхрийн нүд.jpg"],
    available: true,
    id: "y2QxboNT6jK6uKEc2k3M",
    name: "Компод-үхрийн нүд",
    updatedAt: { _nanoseconds: 527000000, _seconds: 1627213879 },
    price: "8500",
    size: "1ш",
    catalog: ["Боловсруулсан хүнс"],
    keyWords: ["гурил", "гоймон", "шпагетти"],
  },
  {
    available: true,
    name: "Зөгийн бал нимбэгний уусмал",
    images: [
      "https://cdn.geresee.tk/tea_coffee/Зөгийн бал нимбэгний уусмал.jpg",
    ],
    keyWords: [],
    id: "yA6Mk5gzFHLBEiu4MHVI",
    size: "1ш",
    updatedAt: { _seconds: 1627213870, _nanoseconds: 453000000 },
    price: "30000",
    catalog: ["Цай, кофе"],
  },
  {
    id: "yuSrOos9cRh4H2MQsVmc",
    keyWords: ["fruit"],
    images: ["https://cdn.geresee.tk/Жимс%2C жимсгэнэ/liir.jpg"],
    available: true,
    updatedAt: { _nanoseconds: 280000000, _seconds: 1627213890 },
    name: "лийр",
    catalog: ["Жимс жимсгэнэ"],
    price: "9450",
    size: "1кг",
  },
  {
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    size: "8ш",
    updatedAt: { _nanoseconds: 126000000, _seconds: 1627214006 },
    price: "10000",
    id: "ywf00Qo9eBdT7Uw79LW3",
    available: true,
    images: ["https://cdn.geresee.tk/ahuin_hereglee/selpack_toilet_paper.jpg"],
    catalog: ["Аxуйн хэрэглээ"],
    name: "selpak ариун цэврийн цаас",
  },
  {
    name: "seven up жижиг",
    updatedAt: { _nanoseconds: 986000000, _seconds: 1627213968 },
    available: true,
    keyWords: ["ундаа", "кола", "жүүс", "шүүс", "уух", "ус"],
    size: "0.5л",
    price: "1600",
    catalog: ["Шингэн хүнс"],
    images: ["https://cdn.geresee.tk/us_undaa/seven_up_light.jpg"],
    id: "yzPKIbtnDB8bQr7UM7w3",
  },
  {
    size: "1ш",
    price: "2250",
    updatedAt: { _seconds: 1627214008, _nanoseconds: 99000000 },
    id: "z4bNCxGq3EPsnxLgZTJJ",
    images: ["https://cdn.geresee.tk/ahuin_hereglee/aruin_noiton_alchuur.jpg"],
    available: true,
    name: "ариун нойтон алчуур",
    keyWords: [
      "цаас",
      "вок",
      "угаалгын нунтаг",
      "живх",
      "памперс",
      "аяга таваг угаагч",
      "амны цаас",
      "салфетка",
      "арчуур",
      "ариун цэврийн хэрэглэл",
    ],
    catalog: ["Аxуйн хэрэглээ"],
  },
  {
    images: ["https://cdn.geresee.tk/Нөөшилсөн хүнс/Принглэс-BBQ.jpg"],
    keyWords: ["ноншим", "гоймон", "давсалсан самар"],
    price: "3800",
    available: true,
    size: "1ш",
    name: "Принглэс-BBQ",
    catalog: ["Нөөшилсөн хүнс"],
    id: "z8eb9WcuTOl7P9zV038D",
    updatedAt: { _seconds: 1627213874, _nanoseconds: 133000000 },
  },
  {
    catalog: ["Амттан"],
    updatedAt: { _seconds: 1627213934, _nanoseconds: 527000000 },
    id: "zFrgtaVlRVI7lhj7D85l",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    name: "Тоффифээ",
    size: "1ш",
    images: ["https://cdn.geresee.tk/Амттан/Тоффифээ.jpg"],
    available: true,
    price: "6200",
  },
  {
    updatedAt: { _nanoseconds: 75000000, _seconds: 1627214046 },
    name: "гоё тараг",
    price: "2300",
    keyWords: ["сүү", "тараг", "аарц"],
    size: "2л",
    available: true,
    images: [
      "https://cdn.geresee.tk/Milk_and_milk_products/goy_chavgatai_tarag.jpg",
    ],
    catalog: ["Сүү сүүн бүтээгдэхүүн"],
    id: "zIimBxYJ7f6GxF0QPIjI",
  },
  {
    id: "zj4pJySUGFQRKQsRfYXv",
    price: "2100",
    images: ["https://cdn.geresee.tk/Амттан/Тролли.jpg"],
    size: "1ш",
    keyWords: ["амттан", "шоколад", "чихэр", "жигнэмэг", "компот", "чипс"],
    name: "Тролли",
    catalog: ["Амттан"],
    updatedAt: { _seconds: 1627213962, _nanoseconds: 497000000 },
    available: true,
  },
  {
    catalog: ["Мах махан бүтээгдэхүүн"],
    images: [
      "https://cdn.geresee.tk/Meat_and_meat_products /knacker-chanamal-utalgat-zaidas.jpg",
    ],
    available: true,
    price: "4000",
    keyWords: [],
    updatedAt: { _seconds: 1627213852, _nanoseconds: 34000000 },
    id: "zu7zFkNGbzGvBtOoP8FW",
    name: "Knacker чанамал утлагат зайдас",
    size: "500г",
  },
];
